# Bun configuration file

[test]
# Coverage configuration
coverage = true
coverageReporter = ["text", "lcov"]
coverageDirectory = "./coverage"
coverageSkipTestFiles = true

# Test execution settings
timeout = 30000
bail = false